name: sportway
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  hive: ^2.2.3
  formz: ^0.4.1
  path: ^1.8.2
  path_provider: ^2.0.14
  pinput: ^2.2.31
  flutter_native_splash: ^2.2.19
  google_components:
    path: packages/google_components

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
