name: sportway
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  hive: ^2.2.3
  formz: ^0.4.1
  path: ^1.8.2
  path_provider: ^2.0.14
  pinput: ^2.2.31
  flutter_native_splash: ^2.2.19
  google_components:
    path: packages/google_components
  app_preference:
    path: packages/app_preference
  app_storage:
    path: packages/app_storage
  google_sign_in: ^5.4.4
  cloud_storage:
    path: packages/cloud_storage
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0





flutter:  
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/Tennis.png"
  fullscreen: true
  color: "#E5E5E5"

flutter_icons:
  android: true
  image_path: "assets/images/Tennis.png"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/Tennis.png'


  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
