class AppConstants {
  static const sportInterest = [
    'Football',
    'Tennis',
    'Gulf',
    "Motorsports",
    "Bandy",
    "Skiing",
    "Shooting",
    "Roller skating",
    "Cricket",
    "Rugby",
    "Pool",
    "Darts",
    "Bowling",
    "Ice hockey",
    "Surfing",
    "Larate",
    "Horse racing",
    "Snowboarding",
    "Skateboarding",
    "Cycling",
    "Archery",
    "Fishing",
    "Gymnastics",
    "Figure skating",
    "Rock climbing",
    "Sumo wrestling",
    "Taekwondo",
    "Fencing",
    "Water skiing",
  ];
}
